CUDA_VISIBLE_DEVICES=4 nohup python3 train_joint.py \
--num_train_epochs=3 \
--train_batch_size=2 \
--test_batch_size=4 \
--device=0 \
--test_file_path=./data_dir/test_sample.json \
--train_file_path=./data_dir/train_sample.json \
--pretrained_model_path=./t5_pegasus_torch/ \
--data_dir=./data_dir// \
--output_dir=./output_dir/ \
--span_layer=endpoint  \
--class_size=2 \
--generate_weight=1 \
--class_weight=1  > train_endpoint.hup&

CUDA_VISIBLE_DEVICES=5 nohup python3 train_joint.py \
--num_train_epochs=3 \
--train_batch_size=2 \
--test_batch_size=4 \
--device=0 \
--test_file_path=./data_dir2/test_sample.json \
--train_file_path=./data_dir2/train_sample.json \
--pretrained_model_path=./t5_pegasus_torch/ \
--data_dir=./data_dir2// \
--output_dir=./output_dir2/ \
--span_layer=endpoint  \
--class_size=10 \
--generate_weight=1 \
--class_weight=1  > train_endpoint2.hup&